collect_food:
  chance: 0.3
  max_collect_food: 50
engine:
  hatching_timer: 6
  health_index: 0
  pet_tasks_time: 10
  sadness_index: 1
  time_of_last_check: '2024-05-25T05:07:35.699711'
food:
  collect_index: 2
  hunger_index: 1
  zero_health_index: 10
games:
  list:
    1:
      name: Тест1
      play_index: 1
    2:
      name: Тест2
      play_index: 2
    3:
      name: Тест3
      play_index: 1
    4:
      name: Тест4
      play_index: 2
    5:
      name: Тест5
      play_index: 1
    6:
      name: Тест6
      play_index: 2
    7:
      name: Тест7
      play_index: 1
    8:
      name: Тест8
      play_index: 2
imgs:
  font_path: fonts/Aqum.ttf
  font_size_eggs: 50
  font_size_info: 24
  path_backgrounds_folder: imgs/backgrounds/
  path_eggs_folder: imgs/eggs/
  path_panels_folder: imgs/panels/
  path_pets_folder: imgs/pets/
  path_rooms_folder: imgs/rooms/
journey:
  event_in_journey: 0.5
  min_health: 15
  replace_to: '##'
  words_to_replace: 3
level:
  collecting: 10
  experience: 100
  level_up_for_activity_by_time: 1800
  max_education_buff: 40
  playing: 15
  sleeping: 5
  traveling: 20
play:
  break_play_index: 5
  play_again_index: 15
  play_index: 5
  zero_health_index: 1
secret:
  owner_id: OWNER_ID
  telegram_token: 5683713666:AAEqls37jArqSUBA7EaBfp9f9qxgsTxBQJU
sleep:
  break_sleep_index: 5
  health_sleep_index: 1
  min_sleep_index: 75
  sleep_down_index: 1
  sleep_index: 3
  zero_health_index: 3
