collect_food:
  chance: 0.9
  max_collect_food: 50
engine:
  hatching_timer: 60
  health_index: 1
  health_min_value: 30
  notification_time: 1800
  pet_tasks_time: 300
  sadness_index: 0.3
  time_of_last_check: '2024-05-28T23:40:02.338836'
food:
  collect_index: 2
  hunger_index: 0.1
  min_value: 30
  zero_health_index: -3
games:
  list:
    1:
      name: 💃 | Танцы
      play_index: 3
      sleep: 1
    2:
      name: 🌀 | Лабиринт
      play_index: 2
      sleep: 0.2
    3:
      name: 🎨 | Рисование
      play_index: 1
      sleep: 0.2
    4:
      name: 🏊 | Плаванье
      play_index: 2
      sleep: 1
    5:
      name: 🎲 | Кубик рубика
      play_index: 4
      sleep: 0.3
    6:
      name: 🎵 | Музыка
      play_index: 2
      sleep: 0.3
    7:
      name: 🏎️ | Гонки
      play_index: 4
      sleep: 1.2
    8:
      name: ⚽ | Игра с мячом
      play_index: 2
      sleep: 1.2
imgs:
  font_path: fonts/Aqum.ttf
  font_size_eggs: 50
  font_size_info: 21
  path_backgrounds_folder: imgs/backgrounds/
  path_eggs_folder: imgs/eggs/
  path_panels_folder: imgs/panels/
  path_pets_folder: imgs/pets/
  path_rooms_folder: imgs/rooms/
journey:
  event_in_journey: 0.5
  min_health: 15
  replace_to: '###'
  words_to_replace: 4
level:
  collecting: 10
  experience: 100
  level_up_for_activity_by_time: 300
  max_education_buff: 40
  nothing: 5
  playing: 15
  sleeping: 10
  traveling: 20
play:
  break_play_index: 5
  min_value: 30
  play_again_index: 15
  play_index: 5
  zero_health_index: -10
secret:
  owner_id: OWNER_ID
sleep:
  break_sleep_index: 5
  health_sleep_index: 1
  min_sleep_index: 75
  min_value: 30
  sleep_down_index: 0.1
  sleep_index: 3
  zero_health_index: -12
